name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*

  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  Unit-test-check:
    name: job's name
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Setup angular
        run: npm install -g @angular/cli
      - name: Setup project
        uses: actions/checkout@v3
      - name: Script
        run: |
          echo ====== START NPM CI ======
          npm ci
          echo ====== END NPM CI ======
          echo ====== START test ======
          npm run test-ci
